import { Router } from 'express';
import { login, logout, me, refresh, register } from '../controllers/auth.controller.js';
import { authenticate } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { loginSchema, registerSchema } from '../validators/auth.validator.js';
import { asyncHandler } from '../utils/async-handler.js';
export const authRouter = Router();
authRouter.post('/register', validate({ body: registerSchema }), asyncHandler(register));
authRouter.post('/login', validate({ body: loginSchema }), asyncHandler(login));
authRouter.post('/refresh', asyncHandler(refresh));
authRouter.post('/logout', asyncHandler(logout));
authRouter.get('/me', authenticate, asyncHandler(me));
